http.host: 0.0.0.0
http.port: 9205

indices.query.bool.max_clause_count: 10024

# Uncomment the following lines for a production cluster deployment
#transport.host: 0.0.0.0
#discovery.zen.minimum_master_nodes: 1
