version: '2'

services:
  elasticsearch:
    container_name: magento2elastic5
    environment:
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    restart: always
    build: .
    ports:
        - "9205:9205"
networks:
  default:
    external:
      name: env_default
